name: Run test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:

    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Setup DB
        run: docker compose up -d

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@417ae3ccd767c252f5661f1ace9f835f9654f2b5 # v3.1.0

      - name: Test with Gradle Wrapper
        run: ./gradlew test --info

      - name: Upload Test Report
        if: failure() # テストが失敗した場合にのみ実行
        uses: actions/upload-artifact@v3
        with:
          name: test-report
          path: build/reports/tests/test/

      - name: Check for Test Report
        run: ls -R build/test-results/test/

      - name: Discord
        uses: sarisia/actions-status-discord@v1
        if: always()
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK_URL }}
          with:
          status: ${{ job.status }}

